// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKNrLsTQOEwRxoz3TtWzfpc20Do74Q1G0',
    appId: '1:262293228104:web:452d3fac39dde507e0667d',
    messagingSenderId: '262293228104',
    projectId: 'proje-7610f',
    authDomain: 'proje-7610f.firebaseapp.com',
    storageBucket: 'proje-7610f.appspot.com',
    measurementId: 'G-YGXQD9H3F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgt-zcxpeFpMNMdcRWMC1Qy7ZYbftYcdU',
    appId: '1:262293228104:android:407fbd6e1a030fc2e0667d',
    messagingSenderId: '262293228104',
    projectId: 'proje-7610f',
    storageBucket: 'proje-7610f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATpboO6YSD7zOvoHriioPLeVC4eMk1VM4',
    appId: '1:262293228104:ios:650377b32b0076d8e0667d',
    messagingSenderId: '262293228104',
    projectId: 'proje-7610f',
    storageBucket: 'proje-7610f.appspot.com',
    iosBundleId: 'com.example.mobilproje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATpboO6YSD7zOvoHriioPLeVC4eMk1VM4',
    appId: '1:262293228104:ios:0a5938c8a93e72d8e0667d',
    messagingSenderId: '262293228104',
    projectId: 'proje-7610f',
    storageBucket: 'proje-7610f.appspot.com',
    iosBundleId: 'com.example.mobilproje.RunnerTests',
  );
}
